{
  pkgs,
  username,
  ...
}: let
  # Custom Wezterm/Alacritty Terminal dropdown script, needed to use it for
  # proper Wayland Copy/Paste support with Helix IDE, alternative
  # used 'tdrop' was X11/XWayland
  # alacritty_dropdown = pkgs.writeShellScriptBin "alacritty-dropdown" ''
  #   export KDOTOOL="${pkgs.kdotool}/bin/kdotool"
  #   export ALACRITTY="${pkgs.alacritty}/bin/alacritty"
  #   ${builtins.readFile ./alacritty-dropdown.sh}
  # '';
  wezterm_dropdown = pkgs.writeShellScriptBin "wezterm-dropdown" ''
    export KDOTOOL="${pkgs.kdotool}/bin/kdotool"
    export WEZTERM="${pkgs.unstable.wezterm}/bin/wezterm"
    ${builtins.readFile ./wezterm-dropdown.sh}
  '';
in {
  # WezTerm - powerful cross-platform terminal emulator with image support
  programs.wezterm = {
    enable = true;
    package = pkgs.unstable.wezterm;
    enableZshIntegration = true;
  };

  home.packages = [
    wezterm_dropdown
  ];

  # Zellij config
  programs.zellij = {
    enable = true;
    package = pkgs.unstable.zellij;
  };

  # Config file for Zellij
  home.file = {
    ".config/zellij/config.kdl".source = ../../../dotfiles/zellij/config.kdl;
  };

  home.file = {
    # Wezterm config file
    ".config/wezterm/wezterm.lua".source = ../../../dotfiles/wezterm/wezterm.lua;
  };

  # NOTE: Only use with Zellij
  #
  # Creates a file which will contain the full nix store path to zellij,
  # used by the main wezterm.lua file
  home.file.".config/wezterm/nix_paths.lua".text = ''
    -- Generated by Nix; do not edit.
    local M = {}

    M.zellij = "${pkgs.zellij}/bin/zellij"

    return M
  '';
}
