{
  pkgs,
  username,
  ...
}: let
  # Custom Alacritty Terminal dropdown script, needed to use it for
  # proper Wayland Copy/Paste support with Helix IDE, alternative
  # used 'tdrop' was X11/XWayland
  alacritty_dropdown = pkgs.writeShellScriptBin "alacritty-dropdown" ''
    export KDOTOOL="${pkgs.kdotool}/bin/kdotool"
    export ALACRITTY="${pkgs.alacritty}/bin/alacritty"
    ${builtins.readFile ./alacritty-dropdown.sh}
  '';
in {
  # Alacritty Config (Fast GPU-Accelerated Terminal)
  programs.alacritty = {
    enable = true;
    settings = {
      window.decorations = "None";
      window.opacity = 0.85;
      font.normal.family = "CaskaydiaCove Nerd Font Mono";
      font.normal.style = "Regular";
      font.size = 11.0;
      terminal.shell.program = "${pkgs.unstable.zellij}/bin/zellij";
      terminal.shell.args = ["attach" "--create" username];
      keyboard.bindings = [
        {
          key = "F";
          mods = "Control";
          mode = "~Search";
          action = "SearchForward";
        }
      ];
    };
  };

  home.packages = [
    alacritty_dropdown
  ];

  # Zellij config
  programs.zellij = {
    enable = true;
    package = pkgs.unstable.zellij;
  };

  # Config file for Zellij
  home.file = {
    ".config/zellij/config.kdl".source = ../../../dotfiles/zellij/config.kdl;
  };

  # WezTerm - powerful cross-platform terminal emulator with image support
  programs.wezterm = {
    enable = true;
    package = pkgs.unstable.wezterm;
    enableZshIntegration = true;
  };

  home.file = {
    # Wezterm config file
    ".config/wezterm/wezterm.lua".source = ../../../dotfiles/wezterm/wezterm.lua;
  };

  # NOTE: Only use with Zellij
  #
  # Creates a file which will contain the full nix store path to zellij,
  # used by the main wezterm.lua file
  home.file.".config/wezterm/nix_paths.lua".text = ''
    -- Generated by Nix; do not edit.
    local M = {}

    M.zellij = "${pkgs.zellij}/bin/zellij"

    return M
  '';
}
