keys:
  - &mbp age1ampggagplvarh46cn05esrlwsn5nj0t9he9n7dxjdtk0vaz99e0q66wp5g
  - &anya age1jjssarkszlhjjhqnamse82rdl8yqwamjczlcya5dkqqltj43pp4qa0psj3
  - &dockerhost age1pe0vvrjeu8g5cgugxvrjcwlg75ls59g6uc0su0x4e2ypwmknu5jqj9nkj2
  - &beltanimal age1s42l4ucujcv59krzuxw3xmrqcyu8v5d8ctad6a0kmhlc4zttxfxqvtuy3l
  - &hummingbird age1aueh50lp9pj5qfm2gm7qezdz4h7wgsjvyktrfj4xlfz548junv3qpk5f7n
  - &tailscale age1q8x3pn8vug94pj759n28e3nkt4yt39p30se978etn9497ass842sk8ge6l
  - &router age18z269exslvey625ry52eu96rhs63vqlyfw4efcxfq8evhup8y46sjytyyq
  - &jellyfin age1mhdepy4r6zvxvgeawq9v7976d0gt48w98pz02zqzq5wkcn7gdcuq0ju8fc
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *mbp
      - *anya
      - *dockerhost
      - *beltanimal
  - path_regex: hosts/tailscale/secrets.ya?ml$
    key_groups:
    - age:
      - *tailscale
  - path_regex: hosts/hummingbird/secrets.ya?ml$
    key_groups:
    - age:
      - *hummingbird
      - *mbp
  - path_regex: hosts/jellyfin/secrets.ya?ml$
    key_groups:
    - age:
      - *mbp
      - *anya
      - *beltanimal
      - *jellyfin
  - path_regex: hosts/router/secrets.ya?ml$
    key_groups:
    - age:
      - *mbp
      - *anya
      - *beltanimal
      - *router
