keys:
  - &mbp age1ampggagplvarh46cn05esrlwsn5nj0t9he9n7dxjdtk0vaz99e0q66wp5g
  - &anya age14n2qzcnrs62xa7pskhp09m3mxapum3mpgh7mncs9nmcnzx2p3pcq8m08uq
  - &nixtest age1pkg5mdawwfpmlg0xcezwndmq2ev4mtrvarlfz08e4tmmpwmr096s0vuqzu
  - &dockerhost age1gntkld4eesqhxq9ugr53lmdwzhqxztljy2pyylj3a4037nfvdq2qfegpfs
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *mbp
      - *anya
      - *nixtest
  - path_regex: hosts/dockerhost/secrets.ya?ml$
    key_groups:
    - age:
      - *dockerhost
