keys:
  - &mbp age1ampggagplvarh46cn05esrlwsn5nj0t9he9n7dxjdtk0vaz99e0q66wp5g
  - &anya age1jjssarkszlhjjhqnamse82rdl8yqwamjczlcya5dkqqltj43pp4qa0psj3
  - &dockerhost age1gntkld4eesqhxq9ugr53lmdwzhqxztljy2pyylj3a4037nfvdq2qfegpfs
  - &beltanimal age1s42l4ucujcv59krzuxw3xmrqcyu8v5d8ctad6a0kmhlc4zttxfxqvtuy3l
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *mbp
      - *anya
      - *dockerhost
      - *beltanimal
  - path_regex: hosts/dockerhost/secrets.ya?ml$
    key_groups:
    - age:
      - *dockerhost
  - path_regex: hosts/beltanimal/secrets.ya?ml$
    key_groups:
    - age:
      - *beltanimal
  - path_regex: hosts/anya/secrets.ya?ml$
    key_groups:
    - age:
      - *anya
