keys:
  - &mbp age1ampggagplvarh46cn05esrlwsn5nj0t9he9n7dxjdtk0vaz99e0q66wp5g
  - &anya age1jjssarkszlhjjhqnamse82rdl8yqwamjczlcya5dkqqltj43pp4qa0psj3
  - &dockerhost age1pe0vvrjeu8g5cgugxvrjcwlg75ls59g6uc0su0x4e2ypwmknu5jqj9nkj2
  - &beltanimal age1s42l4ucujcv59krzuxw3xmrqcyu8v5d8ctad6a0kmhlc4zttxfxqvtuy3l
  - &hummingbird age1aueh50lp9pj5qfm2gm7qezdz4h7wgsjvyktrfj4xlfz548junv3qpk5f7n
  - &tailscale age1q8x3pn8vug94pj759n28e3nkt4yt39p30se978etn9497ass842sk8ge6l
  - &router age1k26plnlstgd0m7zaxrregh3nct6mqhlcw2tsld5arhsgv7c42y4qdrjzyg
  - &jellyfin age16jp9vq7tv6620gr60teel5l39cy8ucmulqm3p9ygg3hycu00ef9sazhtje
  - &example age1f7r6gpqhchzyt4eh8uq7atpp6n0pzguh7je935hnkjmdv52z44wquez0yd
creation_rules:
  - path_regex: secrets/default.ya?ml$
    key_groups:
      - age:
          - *mbp
          - *anya
          - *beltanimal
          - *dockerhost
          - *jellyfin
  - path_regex: secrets/example.ya?ml$
    key_groups:
      - age:
          - *mbp
          - *anya
          - *beltanimal
          - *example
