{inputs, ...}: {
  flake.modules.homeManager.terminal = {pkgs, ...}: {
    imports = [
      inputs.self.modules.homeManager.kde-dropdown-terminal
    ];

    # WezTerm - powerful cross-platform terminal emulator with image support
    programs.wezterm = {
      enable = true;
      package = pkgs.unstable.wezterm;
      enableZshIntegration = true;
    };

    # Zellij config
    programs.zellij = {
      enable = true;
      package = pkgs.unstable.zellij;
    };

    # Config file for Zellij
    home.file = {
      ".config/zellij/config.kdl".source = ../../dotfiles/zellij/config.kdl;
    };

    home.file = {
      # Wezterm config file
      ".config/wezterm/wezterm.lua".source = ../../dotfiles/wezterm/wezterm.lua;
    };

    # NOTE: Only use with Zellij
    #
    # Creates a file which will contain the full nix store path to zellij,
    # used by the main wezterm.lua file
    home.file.".config/wezterm/nix_paths.lua".text = ''
      -- Generated by Nix; do not edit.
      local M = {}

      M.zellij = "${pkgs.unstable.zellij}/bin/zellij"

      return M
    '';
  };

  flake.modules.nixos.terminal = {
    imports = [
      inputs.self.modules.nixos.kde-dropdown-terminal
    ];
  };
}
