{
  flake.modules.homeManager.terminal = {pkgs, ...}: {
    # WezTerm - powerful cross-platform terminal emulator with image support
    programs.wezterm = {
      enable = true;
      package = pkgs.unstable.wezterm;
      enableZshIntegration = true;
    };

    # TODO: Toggle terminal stuff (wip)
    home.packages = with pkgs; [
      local.kwin-toggleterminal
    ];
    home.file.".local/share/kwin/scripts/toggleterminal".source = "${pkgs.local.kwin-toggleterminal}/share/kwin/scripts/toggleterminal";

    # Hotkey configuration for kwin-toggleterminal KWin Hotkey #0
    programs.plasma.configFile."kwinrc"."Script-toggleterminal" = {
      "0_windowClass".value = "org.wezfurlong.wezterm";
      "0_launchCommand".value = "/home/tk/.nix-profile/bin/wezterm";
      "0_hideOnFocusLoss".value = true;
    };

    programs.plasma.shortcuts.kwin."ToggleTerminal_0" = ["Alt+Space"];

    # Zellij config
    programs.zellij = {
      enable = true;
      package = pkgs.unstable.zellij;
    };

    # Config file for Zellij
    home.file = {
      ".config/zellij/config.kdl".source = ../../dotfiles/zellij/config.kdl;
    };

    home.file = {
      # Wezterm config file
      ".config/wezterm/wezterm.lua".source = ../../dotfiles/wezterm/wezterm.lua;
    };

    # NOTE: Only use with Zellij
    #
    # Creates a file which will contain the full nix store path to zellij,
    # used by the main wezterm.lua file
    home.file.".config/wezterm/nix_paths.lua".text = ''
      -- Generated by Nix; do not edit.
      local M = {}

      M.zellij = "${pkgs.unstable.zellij}/bin/zellij"

      return M
    '';
  };

  flake.modules.nixos.terminal = {pkgs, ...}: {
    # This provides dropdown terminal functionality, but specifically
    # for KDE Plasma (probably doesn't work anywhere else)
    environment.systemPackages = with pkgs; [
      local.dbus-app-launcher-bin
    ];

    # # This adds the kwin-toggleterminal script available in KWin
    # environment.pathsToLink = ["/share/kwin/scripts"];

    # This makes dbus-app-launcher available on the dbus
    services.dbus = {
      enable = true;
      packages = [
        pkgs.local.dbus-app-launcher-bin
      ];
    };
  };
}
