{
 "title": "Main Status (Immutable)",
 "description": "Dashboard which shows the status of basically everything in my homelab.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_http_status_code,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_http_status_code{job=\"$job\"},instance)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(nix_auto_update_status,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "nix-auto-update", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$host",
   "type": "canvas",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "repeat": "host",
   "targets": [
    {
     "expr": "nix_auto_update_status{instance=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nix_auto_update_last_run_date{instance=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nix_auto_update_last_update_date{instance=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nix_auto_update_last_update_prev_sha{instance=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nix_auto_update_last_update_current_sha{instance=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "hosts information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=\"node-systemd\"})by(instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"node-systemd\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"node-systemd\",mode='system'}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"node-systemd\"} / (node_memory_MemTotal_bytes{job=~\"node-systemd\"})))* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"node-systemd\",fstype=~\"ext.?|xfs|zfs\"}-node_filesystem_free_bytes{job=~\"node-systemd\",fstype=~\"ext.?|xfs|zfs\"}) *100/(node_filesystem_avail_bytes {job=~\"node-systemd\",fstype=~\"ext.?|xfs|zfs\"}+(node_filesystem_size_bytes{job=~\"node-systemd\",fstype=~\"ext.?|xfs|zfs\"}-node_filesystem_free_bytes{job=~\"node-systemd\",fstype=~\"ext.?|xfs|zfs\"})))by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  { "title": "TrueNAS Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Disk status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "truenas_disk_state", "legendFormat": "{{pool}}/{{disk}}" }
   ]
  }
 ]
}