{pkgs, ...}: {
  # WezTerm - powerful cross-platform terminal emulator with image support
  programs.wezterm = {
    enable = true;
    package = pkgs.unstable.wezterm;
    enableZshIntegration = true;
  };

  home.file = {
    # Wezterm Hammerspoon dropdown config
    ".hammerspoon".source = ../../dotconfigs/hammerspoon-wezterm;

    # Wezterm config file
    ".config/wezterm/wezterm.lua".source = ../../dotconfigs/wezterm/wezterm.lua;

  };

  # NOTE: Only use with Zellij
  #
  # Creates a file which will contain the full nix store path to zellij,
  # used by the main wezterm.lua file
  home.file.".config/wezterm/nix_paths.lua".text = ''
    -- Generated by Nix; do not edit.
    local M = {}

    M.zellij = "${pkgs.zellij}/bin/zellij"

    return M
  '';
}
