tailscale: ENC[AES256_GCM,data:qFXCTfUmmdaqC20vLLFs6UeuaZk4YlSRH2Kip34mxtpN+MM185ulGtZz8hBAEgII5Uuq4gTbKnV0Tu226OhFhdSOo+PrlVp5+22SsVZ013w=,iv:UvKYsZpr/Gvq7CxRhvsn0pDDjbeoLFsnU5/KaKZHXZE=,tag:PYUc6QHh3RLPXtNDTSnM/A==,type:str]
smbcred: ENC[AES256_GCM,data:LkdINJFCvi6/GSuk8wXqcQtRA6Nfda8MwxGSMUaEDZ81JvxUnSBk7lR/,iv:SrfmzO/xDC6v9BYUhaS5n7wMDEng/6jYpoNa0Z75A3A=,tag:VMjok369NvE36y9G9U2zjA==,type:str]
sops:
    age:
        - recipient: age1jjssarkszlhjjhqnamse82rdl8yqwamjczlcya5dkqqltj43pp4qa0psj3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d3RMdEU1dTB2RUlWWTA5
            VmdJQVhNcTZVL3hMRzNlZ3pKZzJsU1U0aUc0Cmd3WDNUdUZuQTdmdFY1MUNOK1Rt
            TnRkMDAyK2lPUUoxd2J3WjVqUXdsY1kKLS0tIFIxaUV5K2NveHhNbWpVS0pCYjRH
            OEZlbk0rY29kTW9TTDViUCtMK2NuV3MK9p5ADV9qfbgAjQbl+YCQy78QeSftlCHw
            uGrzxvvCpbHPpzO9OwpsbnKBN+L5CEbLhhSgHgsWhe5AE0UPPgNwIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s42l4ucujcv59krzuxw3xmrqcyu8v5d8ctad6a0kmhlc4zttxfxqvtuy3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbDhvTUhZK2JFMUtzT0Z5
            ejJvZTB0QUFCUzNrSzFWaXQrd2g5TjB4WEdZClFPVTFqbTNJNUs1ODFZNzB1bkF6
            QWZDN3R2M1pLN3RMS09zYXpOWW1FQWsKLS0tIC92REtGVUpCZzUwWk11SFNBR0hm
            bXJXNHJBbDhKUGhacXhZMVZZNE43TFkKjECLTLssfVK+thTGTm7qBf9po7zwti4A
            nXmuJBOJGwydxzh62CCiO8xWbFMx7Tmu12SUxQPbRcb4QKbqxNbj4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzytvhm49dulgdkhwjs3skkjjpau2h6hvha0t2zrkyzrzkx2qsxqnlmzry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaUt5WDFXZHRxaXBTRFBz
            bnRHdCtObzM5YVhpc2N3QXozZFNuU29PK0ZVCkcwcnBuSEZCN3ZMSGxiMTJoN2sv
            bW5MeC9zc2VoTVNLLzkxMEYzOTZoc3cKLS0tIHlhVTI3ODlwVlF2VlJBSEw5STFk
            WWRhU2ROWW9Fc0VRbS9hV2tzUkRiSE0KAjHn+yjiN5JXdRbxwYvdfHEFavCGQnEQ
            o7E66fEeUIqB3+YjYV9JFRynuJlqy/JF+/NacfpEa4j3A4TF5ULrKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pe0vvrjeu8g5cgugxvrjcwlg75ls59g6uc0su0x4e2ypwmknu5jqj9nkj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcHdtb2xodHhYcDNiL2Nz
            TGlhYmhLMHhvS0QwMGVjLzJMOEMwUFFQOVFRCkVkb2IxSzIxbERBY2ZkbktxdTB6
            S0RyeUpMRHp6aFl4MjJ2ekltWFZPZTAKLS0tIFR2cGY4ajVlQWVkTmRDb1BsMWtk
            cmQ3UVFlU2J2blZKUEEvZ3d5ZHYwQ1kKeuOJUOjebgW2hdQKixo5zJEct+XSDoIO
            9MGVwEEk4hmn0gIODzrrp3AA/JjWGUsLhz3Jp47JajJ/yFFwzEa9Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16jp9vq7tv6620gr60teel5l39cy8ucmulqm3p9ygg3hycu00ef9sazhtje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLakVnang1RExMREpRdHNR
            NlVpRDhUTTlRenI1QlplRWdzOUdBbmsya1M0CnEyZVZFbkEzcXA1ZitaRHRTaTBz
            N25STmRRNHN5WG9sOGNFKy9qZjV6TlUKLS0tIGxBbUpJQkExZjNlQWNzU2ZvWW81
            VXBrbWZrdDczNEJhL0dUdUVZOUJHSDAK+wBtw7NvXU9i5oH8m9d9iNgaLEf2C39y
            xGg3g4x+3JioW7e1riW7J6cxlgXPC0QntFT8GpZYWO/OzNY9x4U3xQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jszu95jrd579t9xe4ltfzsu5pvv0g4f70w96knmyuk9shwd259uqjx0zmn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWJDYXh3THRUMlQvZW83
            VnREV3hkenZyS05IcG1nZzkxSVZJcFdocTBVCk5KdmpMRmFKZWZ2WWlaOTdFTWU1
            dDViSDhlN1YvaVk5QWhoRVVHN21ZaTAKLS0tIDdGVjZrQ0ZIMDJDMk02eG5BSitq
            eGY5dmI4VlNqMkxUd3VkTmdIWStWbm8Ko3yrh2frkSuopOSc2mapyNK+LmLqUTKP
            hROYUY9oR0eiWFrPKgyTlLxj5zCm8bHvVU8em6PsB0HJFvmN9SniRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q8x3pn8vug94pj759n28e3nkt4yt39p30se978etn9497ass842sk8ge6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4S3BNMENOQWh3SkpvTG9X
            aXJOVlNZMEFqQk1yUWpscmZyZCtXamp6b1RnCkVnOVJLQXBPZ1NnMnEzR0FOVmUy
            SFdFRnFNT0p6bjA1RlRSK3E4NWNUK0EKLS0tIFpSM2R0R2pOdUg0a2lmVHA1S3Jm
            QVZpai9JNktibVl1UnJNaHUwYkIzaFkK7ACC4qBiCntd2H3ZphydCsKAUv0ESaVd
            13WeAd6MzhCeKPKnpCpCkogMDwfXEGzdAx5B3SE1txAvKnB5QbfEVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12rass7kjv34f2nhth4c0d4fr56g09c7lhmas0tftym43xdl2lgeqf6vgcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU291ZngwNVhPRjhvQnMv
            RExsRkNNM21HOVRRUjh2aFR6aldtdVd6Rm04CjBMWW5UUTI1MERyNzBRL0dwRy9i
            SjBjaXhualhCendvUEZKUG1BcHIxcFkKLS0tIFBjSFpPZnUyMmtocy9qczMrU3pS
            LzRGaVNJdXZ5SS9JQVVaS2hTbDgvSEEK15ySPkDAaZJy9bC+RKzLcDKnglVYckKZ
            62C6mC4y1uhbrTbXOjVqTQDLNrwn7st1loKNeylafEGTl+K+7+0OjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T14:56:08Z"
    mac: ENC[AES256_GCM,data:OvpexSV2FNBmHNNYyiCRWP8ktgWUcGj/K+q6Ibypk/EMUhivNZJF4tJPfCnsIBnmUXpwOzSRSJsZCX7N2TCei4HMVlN9i8YlxX13l+gXqY3ErWg3gFmBYnxuIeIsNCjiv7v8HSEpmsGg+tVJwnnpKmrkpIL1znvPmzFH5BWhzJQ=,iv:RuUgbN6ujGZ3g8gooSrRhGUwsNeK6F7JX2aUyS7ve+g=,tag:S8X70cVFNmKuU6DiXvQu9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
