tailscale: ENC[AES256_GCM,data:qFXCTfUmmdaqC20vLLFs6UeuaZk4YlSRH2Kip34mxtpN+MM185ulGtZz8hBAEgII5Uuq4gTbKnV0Tu226OhFhdSOo+PrlVp5+22SsVZ013w=,iv:UvKYsZpr/Gvq7CxRhvsn0pDDjbeoLFsnU5/KaKZHXZE=,tag:PYUc6QHh3RLPXtNDTSnM/A==,type:str]
smbcred: ENC[AES256_GCM,data:LkdINJFCvi6/GSuk8wXqcQtRA6Nfda8MwxGSMUaEDZ81JvxUnSBk7lR/,iv:SrfmzO/xDC6v9BYUhaS5n7wMDEng/6jYpoNa0Z75A3A=,tag:VMjok369NvE36y9G9U2zjA==,type:str]
sops:
    age:
        - recipient: age1jjssarkszlhjjhqnamse82rdl8yqwamjczlcya5dkqqltj43pp4qa0psj3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcWVjcW95N0p3UGFWN2l6
            NGRXbHBKTzhPOEhKajl3WVNDTFB2cW9QRUI0CjVJeDk4TVcyelg5SFpPbERKRFEy
            MGNFMmlFZE5zMXV2Zm90T0ErU0kzYzgKLS0tIHl2bW5ETk93S1JNdTIvOWZDRENF
            WXJPemFpRGtRejZHV0JrMnM0c3plWU0Kk6Bvs2g8+YFHg5Ef46PtdMqDn8jRxzc3
            ouYo8Qr9pt2tBY+YJAhxI8zlcA0LqSgLnaix/VIgFi/KeIlrZzbqmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s42l4ucujcv59krzuxw3xmrqcyu8v5d8ctad6a0kmhlc4zttxfxqvtuy3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUXhXUHpIVFR1UFp1TXZM
            MFRrQzdxdXArY1g3RUVQem5TUis4aEpuZlZzCnl3eXdvdEFWd3dqNFl0UTZmV20v
            N1UwUE8zM3ZqLzY5K0JabGNsVFREd00KLS0tIGNFMXgxUzI4cFp6VjZkWkQ3U1BD
            T2tiU2hrZHg4Q3cvMWlQM1dsa3dUVW8KO5Dq816mWYsROXAuc/JltGofUuBt9CZP
            xN0qYnCHSvi3blr89aaD4d3MTXH1SuWcAuGfvM9K48cJ0R6pH9SIRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzytvhm49dulgdkhwjs3skkjjpau2h6hvha0t2zrkyzrzkx2qsxqnlmzry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV2c2Y0JGRkUzN0ZFLzBp
            TFNqa09rUFkyS2tLeTdDSlRPNThXNlludW1rCnRTNEJ6R0c2WjVzRWpVUjhwTXMy
            Y0dtMCtseU1FSjNJN3Fjc2JnNFVyYUUKLS0tIEtFV2ZlT0hGZFZxOXNsTFQ2LzFS
            Mzl5RjB1SithU2tpMmRKNlhCdmhzTkUKKFLUwYS007OrNf8LSIZEojisqFa8iAkF
            u6zRrEQaOKZD5fvSEkBfvyDTdxZWQppS+ZViut3Y8llTzXE3rkvEXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pe0vvrjeu8g5cgugxvrjcwlg75ls59g6uc0su0x4e2ypwmknu5jqj9nkj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSE9DV2hBUjZEWDB1dEJL
            eitzT25BUkEzdmhoZVhycUFGN0pnZWpZNEFnCjNXT1Q1THhaSDNHQ3Y3Mi9ST2Uv
            cHVDREwvNnpMdkVMSmxjVmNKeE8yVHMKLS0tIDJjbjFaSGxQM1o2bWdIVU55NFpO
            SFdTd1VqM2RneGtNRm9xKzltK3o3QXcKyHp+loaaUxg9kJYmC99b/ea4ZBSiBfeC
            fBlypKRSTDT29Pp17b8o6jsmZMBwweWglGq90Yfv7y5Xv1HVc9CCBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16jp9vq7tv6620gr60teel5l39cy8ucmulqm3p9ygg3hycu00ef9sazhtje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bDZ4bENYWVN3a1hYNFQ4
            OHpJVlVYazhYeUpzc1NKL3lKekkxSnRvdWc0CjFqSDV1UFFXeFhrZkJoVnlwKzRB
            cWdqNm1sdy91cVcvamxBOGRkSG4xYlUKLS0tIEFFdEU3ekNGcUkybmx0VmEvazZJ
            TDd4cSs4b3J5Zkk2S3N1bStIZGk3eXMKSl0mF/dIvRCJI7igCTySa/6twGJQZtyZ
            /L1VCnKiP9LzowQfrJ/wGSpmgHEAVnKgaOdem5Tptp2oYerhAVGa1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jszu95jrd579t9xe4ltfzsu5pvv0g4f70w96knmyuk9shwd259uqjx0zmn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a09jNk8zMG9TcmtPWXFa
            c2lWUVlXN1FGRHRJSTc1MStPdlRxOTdhVEI4CjlYMjhSZ3hMdGhoNHEycnhOQkhp
            Tzd4N09RWjErRkNXQnR0MU1vY2dOaEEKLS0tIHBScU9rcDVUT21SMDdTc2IydDk2
            Y2Z4VENnM01nWVdvR2VZVnJYajZVV00K1WtCr4Joirm5e+0uSL9t92uW9rtfSdaw
            t7MkwDozAK3NDJyVMdfgkGKWpmTV1zMPYvxecaAFeexKPtli06Y5xQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12rass7kjv34f2nhth4c0d4fr56g09c7lhmas0tftym43xdl2lgeqf6vgcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTmpRNndtVmNSZHg5MHB4
            dzJTTUxWWTVlRDk1dW95eDhnWHFoYnNjNmtNCnEzNHV3UU5iUHl0QVRabVVrOGpB
            eWQwSDJwVUFFd202TXQxSlBRZC9HVmsKLS0tIFJYWVZEdFp4ZER3anVSWWRBbkdx
            Q1lNbWUxSFZZSE9keURuZmw3QnQ2N2sKeescxjHT43mT5HJikRJwGCEtkFSV+6S4
            8Rcote9pwb1BgRXS4nkqyJ0qf1NmbeodqKb2jxaeX2xsn9ufI+hnkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T14:56:08Z"
    mac: ENC[AES256_GCM,data:OvpexSV2FNBmHNNYyiCRWP8ktgWUcGj/K+q6Ibypk/EMUhivNZJF4tJPfCnsIBnmUXpwOzSRSJsZCX7N2TCei4HMVlN9i8YlxX13l+gXqY3ErWg3gFmBYnxuIeIsNCjiv7v8HSEpmsGg+tVJwnnpKmrkpIL1znvPmzFH5BWhzJQ=,iv:RuUgbN6ujGZ3g8gooSrRhGUwsNeK6F7JX2aUyS7ve+g=,tag:S8X70cVFNmKuU6DiXvQu9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
