tailscale: ENC[AES256_GCM,data:qFXCTfUmmdaqC20vLLFs6UeuaZk4YlSRH2Kip34mxtpN+MM185ulGtZz8hBAEgII5Uuq4gTbKnV0Tu226OhFhdSOo+PrlVp5+22SsVZ013w=,iv:UvKYsZpr/Gvq7CxRhvsn0pDDjbeoLFsnU5/KaKZHXZE=,tag:PYUc6QHh3RLPXtNDTSnM/A==,type:str]
smbcred: ENC[AES256_GCM,data:LkdINJFCvi6/GSuk8wXqcQtRA6Nfda8MwxGSMUaEDZ81JvxUnSBk7lR/,iv:SrfmzO/xDC6v9BYUhaS5n7wMDEng/6jYpoNa0Z75A3A=,tag:VMjok369NvE36y9G9U2zjA==,type:str]
sops:
  age:
    - recipient: age1ampggagplvarh46cn05esrlwsn5nj0t9he9n7dxjdtk0vaz99e0q66wp5g
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MTFPUmI3aGZPQ2YweUwv
        MnZnc0IvNVBpVWZoZmFjNU1FaXlrT2R6YTNJCmpDVzhKWTNCM01waitsZnNRaGlG
        WmJ3dFlXbWF0WHZscmEyV01wRkNpaGcKLS0tIDFuMTk5UXJTK21sbHBrdFhMUnNo
        T1BKbmcyK05RMjVRemc5UW5wa0xQVEEKT9e2DpnyxVZdyP+zhmhibQXJgNT+J6PX
        E0yapULfzurhH3QGfI2QAG19LfCDQ0kWwvobcbwcDZJ2qI5TRgxNdw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jjssarkszlhjjhqnamse82rdl8yqwamjczlcya5dkqqltj43pp4qa0psj3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4czRCT2I0aUZrL2lXSU1m
        c0thNVJlTmpoWGFreWRrcktZUXdGbDl5TkRzCi8yajBQeVlic3JlT1ltTHpLdnFR
        em1xMWpDVTY5TTVmaklqclBXWjl1bncKLS0tIEt3TExpYlQzZFRLMFYwUjhiSDRn
        WENoRzlsQlBqZ1E3eHlJK2s0OXFpR1kKXXozbShhK8gP72X55tcB5q04FR29ifdM
        KqGNwFtcAM5f4y6L6pRaBu+344kU5crymlg5e74U3MZq1KPhCcKUQw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pe0vvrjeu8g5cgugxvrjcwlg75ls59g6uc0su0x4e2ypwmknu5jqj9nkj2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZDhkNjJKbDVIRk82TzBR
        UDVkRTY3bFBCOWowUUxjVXN6U2Z0UzBMRFR3CnpYYUNZaXJwMW5MTWFwTk1MUnVl
        RnJHRWFDZll6WkFweDRERnhTaGZmYXcKLS0tIHA1eE1XR29Gd2hxWmIyQkVEZllF
        ZWM4QTlvSXVsc0gxY3d1Q09wU0VJUUUK9rw+2HhGL2m3UpQ8HI6wO65Kqs11XpZE
        cy+STwCfec/1E5ZfswqMgu5iv9wSbK0R0FJ+kRRmlWjLMWGLC7sJJQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1s42l4ucujcv59krzuxw3xmrqcyu8v5d8ctad6a0kmhlc4zttxfxqvtuy3l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOURuVUpud3c0TSs0OWFV
        VnRLMmJoS3h1cnNDZmUxaWNNalFRTGxEYW1BCjFRVFM0WlB3WDZGbGxxOWdVbmI5
        eVBLMG5FTUcrZU1BaDZSYlh3a0FQd0EKLS0tIEZibzI0RTQzNXhSNlFjY2FBWFR2
        YXpSVlJZQjhhUVNrbHFWam1vS1cxSjQKSL/4whReWSBealZ2/VpzeW8ctSk2YC0U
        Lt5b+Sr/xs2gQXwxNf5tzo+8N7txrveFoF363Uva6hWGoP+uidS7Ug==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age16jp9vq7tv6620gr60teel5l39cy8ucmulqm3p9ygg3hycu00ef9sazhtje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMUlWbElWZTJpQjJRUEQ4
        RDdhQ0RLeUVrV2R1MHdVSXVuUzFXblV2N1ZZCk1PL1M1UldESkk1UEtJYnkvMlpC
        NHM5dXd3SThNYkFzVmZNYlBXTXdQZTAKLS0tIHM1TGRuMXYvNXdhSkQvVTNUMnB1
        Z3ZPOFZyczFDeVdqNVFSam9pYU53WUUKViqzW5Hr9pIAm0eZpuqjtnEIPKBJ1ug1
        BcGSl0J1QuqXq5hmCVgsl/wLDnD1B0Jv4Qc0k6rg9Y7x/iOmnt4PUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-16T05:30:05Z"
  mac: ENC[AES256_GCM,data:GXf9mHA5KW1BB2qwQDDw5TxtRVFP3j1dlI41PbuXsoCZ4rWR5NiYjMmOAFjIUhXfa+tDCwYwo91n7uNwFVRLsKlyfckVNQT4uAEAshTErVfrURmX/+RfVRU7iZsepGoDhXD0ZlcNJ/3InwPaZLbsmv8T9iroIrEmt+O2ROQS8PM=,iv:GjkP2rmegsGZOo1+7fBvf5ZSMuoaGEjzDP7jxBoK/74=,tag:VoOsWYDzBvIVT00CudY0Hw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.8.1
